name: Build and Push tts-mandarin for amd64

# Configure Manual Trigger
on:
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: privapps/TTS-Mandarin@main
        with:
          text: '减肥的牲口见料福鼎市李开复但是'
          voice: '18'
          content: 'out.mp3'
      - run: ls -l 
